# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lucky is a lucky man
email: zsney.lzhou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my magic home.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  zslucky

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: zslucky
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Custom variables for theme zslucky
username: Lucky Zhou
avator_url: /assets/img/avator.jpg
jobtitle: Front-end Engineer.
qq: 444950680
weixin: Zsney88
weibo: zsney88
facebook: zsney.lzhou
user_desc: Like open source projects, like sharing.
